# -*- coding: utf-8 -*-
"""python&git_assignment_q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    to view in colab https://colab.research.google.com/drive/1YQ2ccTGYjHXK5ErLS9PqJ74FueJ8OA3B?usp=sharing
"""

import numpy as np
import math

N = int(input())                   # taking input from user, n value
a = 1/(math.log(2))                # just finding the value of log2 for future use
arr = np.ones((1,N))               # forming arrays y and y cap
ycap = np.random.rand(1,N)
y = np.random.randint(0,2,(1,N))

ycap_modified = arr - ycap         # forming i-y and 1-y cap arrays
y_modified = arr - y
ycap_log2 = a*np.log(ycap)         # forming log2(i-y cap) and log2(y cap) arrays
ycap_modified_log2 = a*np.log(ycap_modified)
O_function = (1/N)*(y*ycap_log2 + y_modified*ycap_modified_log2)                # calculating the arrays within the summation in the cross entropy loss function
O_value = 0
for i in range(0,N):               # summing all the values to obtain final result
  O_value = O_value + O_function[0,i]
print(O_value)

