# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IL51j5D7rNG4_Yf_DrCleGMyitI1g-dF
"""

class abc:
    dict = {}
    index = 1
    def input(self):
        self.arr = list(map(int, input().split(' ')))
        self.target = int(input())
    def answer(self):
        n = len(self.arr)
        for i in range(n):
            for j in range(i, n):
                if self.arr[i]+self.arr[j] == self.target:
                    self.dict[self.index] = [i, j]
                    self.dict[self.index+1] = [j, i]
                    self.index = self.index + 2
        print(self.dict)
                    
obj = abc()
obj.input()
obj.answer()