# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wybWUsAhEU5NkuRNf3S__39gTWJl94yw
"""

import numpy as np
import math

n = 100
y = np.random.randint(0,2,n)
ycap = np.random.rand(n)

O = 0
for i in range(n):
    O += y[i]*math.log2(ycap[i]) + (1-y[i])*math.log2(1-ycap[i])
    
O /= -n
print(O)