# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wybWUsAhEU5NkuRNf3S__39gTWJl94yw
"""

import numpy as np

class make_dict:
    arr = [10,20,10,40,50,60,70]
    target = 50
    ans = {}
    
    def compute(self):
        ind = 1
        for i in range(len(self.arr)):
            for j in range(len(self.arr)):
                if(self.arr[i]+self.arr[j] == self.target):
                    self.ans[ind] = [i, j]
                    ind+=1
        print(self.ans)
    
dj = make_dict()
dj.compute()