# -*- coding: utf-8 -*-
"""Tharun Anand M_ED20B068.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k4-zkDL7wjb7kcYmweHYB_sqgmt34aRQ
"""

import numpy as np

"""Question 1"""

n=5

y=np.random.randint(low=0,high=2,size=n)
y

y_hat=np.random.rand(n)
y_hat

O=0
for i in range(0,n,1):
    O=O-(1/n)*(y[i]*np.log2(y_hat[i])+(1-y[i])*np.log2(1-y_hat[i]))

O

"""Question 2"""

class solution:
  
  def __init__(self,input,target):
      self.input=input
      self.target=target
  def find(self,input,target):
      count=0;
      for i in range(0,np.size(input),1):
         for j in range(0,np.size(input),1):
            if input[i]+input[j]==target and i!=j:
              count=count+1;
              output[count]=[i,j];
      return output

C1=solution([10,20,10,40,50,60,70],50)
output=C1.find(C1.input,C1.target)
output

