# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hDUaHJ2z48fVmjUaD0jxasD_aecPykHR
"""

class El_Pairs:
  arr = []
  target = 0
  ans = {}
  
  def input(self):
      self.arr = list(map(int, input().split(' ')))
      self.target = int(input())
      
  def display(self):
      print(self.ans)
      
  def compute(self):
    index=1
    arr_sz=len(self.arr)
    for i in range(0,arr_sz,1):
        for j in range(0,arr_sz,1):
            if self.arr[i]+self.arr[j]==self.target:
                self.ans[index] = [i,j]
                index+=1
    self.display()
  
c1 = El_Pairs()
c1.input()
c1.compute()