# -*- coding: utf-8 -*-
"""Question 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hn7KhvHvQaj0_5LHa9QuuoZWV-9VYxhg
"""

import numpy as np
ycap= np.random.rand(1,100)
y=np.random.randint(0,2,(1,100))
N=100;
y1=np.log2(ycap)
y2=np.log2(1-ycap)
x1=y*y1 
x2=(1-y)*y2
O=np.sum(x1+x2)
O=-O
print(O)