# -*- coding: utf-8 -*-
"""Question_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTz9TYHXDgL0CpUVGeAGilSMq0DxWMXS
"""

import numpy as np

n=int(input('imput n '))
y_hat=np.random.rand(1,n)
y=np.random.randint(0,2,(1,n))
y1=np.log2(y_hat)
y2=np.log2(1-y_hat)
x1=y*y1 
x2=(1-y)*y2
O=np.sum(x1+x2)
O=-O/n
print(O)

