# -*- coding: utf-8 -*-
"""Question_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-SmX-4ox0krTCrogZs9AxhnVJffED79
"""

import numpy as np
class CheckArray:
  z={}
  def __init__(self,arr,target):
    self.arr=arr
    self.target=target

  def checker(self):
    k=1
    a = self.arr
    t = self.target
    for i in range(len(a)):
      for j in range(len(a)):
        if (a[i]+a[j]) == t:
          self.z[k]=[i,j]
          k=k+1
    print(self.z)


arr = input()
target = int(input())
x1 = arr.split()
for i in range(len(x1)):
  x1[i]=int(x1[i])

x = np.array(x1)
c = CheckArray(x,target)
z = c.checker()

