# -*- coding: utf-8 -*-
"""CVI_Ass1_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LsSPFhRuIHURdtoSnn7iVCTZedGbVeuV

Create two vectors 𝑦 and 𝑦̂ having the same dimensions, where 𝑦̂ should consist of random numbers between [0,1) and 𝑦 should contain 0𝑠 and 1𝑠, for example, 𝑦 =[0,1,1,0,1,0,0,1,...,1]. Compute the given expression: Where n = 100, is the total number of elements in y and 𝑦
"""

import numpy as np;
n=100;

y_cap=np.random.rand(1,n);

print(y_cap);

y=np.random.randint(0,2,n);

print(y);

O=(-1/n)*sum((y*np.log2(y_cap)) + ((1-y)*np.log2(1-y_cap)));

print(O);

