# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGnvGlsEqGTGrd5Atbxw7asFHLsCqS_M
"""

class findPairs:
 a=[]
 listPairs={}
 k=0
 n=int(input("Enter the number of elements in array"))
 for i in range(n):
  x=float(input())
  a.append(x)
 print(a) 
 targetSum=float(input("Enter the value of target sum"))
 for i in range (n):
  for j in range(n):
   if(i!=j):
    if a[i]+a[j]==targetSum:
        k=k+1
        listPairs[k]=[i,j]
print(findPairs.listPairs)