# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGnvGlsEqGTGrd5Atbxw7asFHLsCqS_M
"""

import numpy as np
n = 100
y = np.random.randint(0, 2, n)
y_cap = np.random.rand(n)
O= - np.mean(y * np.log2(y_cap) + (1 - y) * np.log2(1 - y_cap))
print(O)