# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1haLCcqOhx18mBCp4SRuqMGfkDaEAi8lR
"""

class find_pairs:
    
    
    def __init__(self, array, target):        
        self.array = array
        self.target = target

    def pair_dict(self):
        
        output = {}
        n = 1
        for i in range(len(self.array)):
            for j in range(len(self.array)):

                if self.array[i]+self.array[j] == self.target:
                  out[n] = [i,j]
                  n += 1

        return output

# receiving input    
array = list(map(int, input().split()))
target = int(input)

fp = find_pairs(array, target)


print(fp.pair_dict())